version: '3.8'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  db:
    image: postgres:16
    restart: always
    container_name: PostgreSQL
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onewresort

volumes:
  redis_data:
