export enum ShopItemSubtypeE {
  GUN = 'Gun',
  RESOURCES = 'Resources',
  EXPLOSIVE = 'Explosive',
  COMPONENTS = 'Components',
  AMMO = 'Ammo',
  ELECTRICAL = 'Electrical',
  TOOL = 'Tool',
  CLOTHES = 'Clothes',
  TEA = 'Tea',
  CARD = 'Card',
  MEDS = 'Meds',
  BLUEPRINT = 'Blueprint',
  SKINS = 'Skins',
}
